
title: ""
subtitle: 
description: >- # this means to ignore newlines until "baseurl:"
  We are a research studio operating collaboratively through ‘rigorous creativity’ to advance AI applications. Working with partners, we support public programming and audience experiences, build AI installations, and provide critical spaces for learning and the creative enquiry of technology.  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  electronic-life


# Build settings
# minimal mistakes
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
plugins:
  - jekyll-feed
collections:
  speculations:
    output: true
    permalink: /:collection/:title/