import type { Metadata } from "next";
import localfont from 'next/font/local'
import './globals.css'

const supremeFont = localfont({
  src: './fonts/Supreme-Variable.ttf',
  display: 'swap'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={supremeFont.className}>
      <body>
        {children}
      </body>
    </html>
  )
}
